data:
  surf_vars: ['Tmin','Tmax','pr']
  static_vars: ['slt','geo']
  patch_size: 40
  patch_stride: 10
  n_hr_views: 2
  n_lr_views: 6
  crop_sizes: [32, 12]
  min_scales: [0.8, 0.2]
  max_scales: [1.0, 0.5] 
training:
  device: 'cuda'
  n_features_swav: 128
  batch_size: 16
  n_prototypes: 30
  learning_rate: 0.0001
  sinkhorn_epsilon: 0.03
  max_patience: 2
  min_epochs: 5
  checkpoints_file_path: checkpoints/
  weights_file_name: null
