data:
  crop_sizes:
  - 32
  - 12
  max_scales:
  - 1.0
  - 0.5
  min_scales:
  - 0.8
  - 0.2
  n_hr_views: 2
  n_lr_views: 6
  patch_size: 40
  patch_stride: 10
  static_vars:
  - slt
  - geo
  surf_vars:
  - Tmin
  - Tmax
  - pr
training:
  batch_size: 16
  checkpoints_file_path: checkpoints/
  device: cuda
  learning_rate: 0.0001
  max_patience: 2
  min_epochs: 5
  n_features_swav: 128
  n_prototypes: 30
  sinkhorn_epsilon: 0.03
  weights_file_name: null
